CLINICAL_PATH: "data/data/Data_Entry_2017.csv"
ADI_PATH: "data/data/WI_2023_ADI_9 Digit Zip Code_v4_0_1.csv"
IMAGES_PATH: "data/images"
PROCESSED_PATH: "data/processed"
STATS_PATH: "data/processed/glob_norm.json"
WEIGHTS_PATH: "data/processed/weights.json"
MASTER_PATH: "data/processed/processed_data.csv"
